# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'CIMS Developer'
        # Default value if no value is explicitly provided
        default: 'CIMS Developer'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# Environment variables
env:
  testvar: '999'
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job will build the app
  build-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      # Runs a set of command using the runners shell
      - name: Input and custom variables
        run: |
          echo "Hello ${{ inputs.name }}",
          echo "testvar = ${{env.testvar}}"

      # Display all env vars
      - name: GitHub environment vars
        run: env

  # This job will build the api
  build-api:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building API"
